release branch: change workflow

diff --git a/.github/workflows/pr.yaml b/.github/workflows/pr.yaml
--- a/.github/workflows/pr.yaml
+++ b/.github/workflows/pr.yaml
@@ -1,28 +1,24 @@
-name: Block Pull Requests with 'Merge branch develop' Commits
-
+name: Block 'Merge branch develop' commits
 on:
+    pull_request:
+        types: [opened, synchronize, reopened, edited]
     push:
         branches:
-            - 'release/*'
-    pull_request_target:
-        types: [opened, synchronize]
-        branches:
-            - 'release/*'
+            - release/**
 
 jobs:
-    block_merge:
-        runs-on: ubuntu-20.04
+    check-merge-message:
+        runs-on: ubuntu-latest
 
         steps:
             -   name: Checkout code
                 uses: actions/checkout@v2
 
-            -   name: Check for 'Merge branch develop' Commits
-                if: |
-                    github.event.pull_request.base.ref == 'develop' &&
-                    github.event.pull_request.head.ref == 'release/*'
+            -   name: Check commit messages
                 run: |
-                    if git log --merges --ancestry-path HEAD^..HEAD --pretty=format:%s | grep -q "Merge branch 'develop'"; then
-                      echo "ERROR: This Pull Request contains a merge commit from 'develop'. Merging from 'develop' is not allowed."
-                      exit 1
-                    fi
+                    for commit in $(git log --pretty=%s HEAD^..HEAD); do
+                      if [[ $commit == *"Merge branch 'develop' into release/"* ]]; then
+                        echo "Error: Commit message similar to 'Merge branch 'develop' into release/' found."
+                        exit 1
+                      fi
+                    done
